# Site settings
title: CoderDojoMilano
email: coderdojomi@gmail.com
description: >
  CoderDojoMilano
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://coderdojomilano.it" # the base hostname & protocol for your site
twitter_username: CoderDojoMi
github_username: CoderDojoMilano

# Build settings
markdown: kramdown
