# Site settings
title: CoderDojo Milano
url: http://www.coderdojomilano.it
description: "CoderDojo Milano - Dedicato a ragazzi e ragazze di età compresa tra i 7 e 17 anni che vogliono imparare a programmare, divertendosi"

# Color settings
color:
  bg: '#17baef'
  navbar: 'rgba(255,255,255,.8)'
  links: '#00f'
  links-focus: '#0ff'

# Socials
social:
  - title: google-plus
    url: https://plus.google.com/+CoderdojomilanoIt
  - title: facebook
    url: https://www.facebook.com/CoderDojoMi
  - title: twitter
    url: https://twitter.com/CoderDojoMi

# Build settings
markdown: kramdown
permalink: pretty

collections:
  - mentors