# Site settings
title: CoderDojo Milano
url: https://coderdojomilano.it
description: "Dedicato a ragazzi e ragazze di età compresa tra i 7 e 17 anni che vogliono imparare a programmare, divertendosi"
storage_uuid: "a26d6629-e365-4dea-8d40-dcf0d1b3a1aa"
timezone: Europe/Rome
future: True

# Color settings
color:
  bg: '#efefef'
  fg: '#3f3f3f'
  navbar: 'rgba(255,255,255,.8)'
  navbar-collapsed: 'rgba(255,255,255,1)'
  links: '#4078c0'
  links-focus: '#00f'

# Socials
social:
  - title: facebook
    url: https://www.facebook.com/CoderDojoMi
  - title: twitter
    url: https://twitter.com/CoderDojoMi

event_locations:
  - id: tagmilano
    url: https://talentgarden.org
    name: TAG Milano
    lat: 45.4973345
    lon: 9.2191134
    logo: logo_tag_milano.png
    addr: Via Merano, 16, 20127 Milano
    no_home_map: true
  - id: wemake
    url: https://wemake.cc
    name: WeMake
    lat: 45.507106
    lon: 9.2262703
    logo: logo_wemake.png
    addr: Via Privata Stefanardo da Vimercate, 27, 20128 Milano
    no_home_map: true
  - id: wcapmi
    url: https://www.wcap.tim.it/en/accelerators/milan
    name: Working Capital Accelerator
    lat: 45.4862554
    lon: 9.2425329
    logo: logo_wcap.png
    addr: Via Rombon, 52, 20134 Milano
    no_home_map: true
  - id: base
    url: https://base.milano.it/
    name: BASE Milano
    lat: 45.452412
    lon: 9.163875
    logo: logo_base.png
    addr: Via Bergognone, 34, 20144 Milano
    no_home_map: true
  - id: unimi-di
    url: //www.di.unimi.it/
    name: Università degli Studi di Milano - Dipartimento di Informatica
    lat: 45.454522
    lon: 9.214693
    logo: logo_unimi.png
    addr: Via Comelico, 39, 20135 Milano
    no_home_map: true
  - id: makershub
    url: //www.makershub.it/
    name: Makers Hub
    lat: 45.5073122
    lon: 9.1617432
    logo: logo_makershub.png
    addr: Via Enrico Cosenz 44/4, 20158 Milano
    no_home_map: true
  - id: incowork
    url: https://www.incowork.it/
    name: inCOWORK
    lat: 45.545692
    lon: 9.160672
    logo:
    addr: Via Po, 77, 20032 Cormano (MI)
    no_home_map: true
  - id: mico
    url: https://www.micomilano.it
    name: MiCo - Milano Congressi
    lat: 45.48092
    lon: 9.1533498
    logo: logo_mico.png
    addr: Viale Eginardo 29, angolo Viale Lodovico Scarampo, 20149 Milano
    no_home_map: true
  - id: ladogana
    url: //ladoganadimilano.com/
    name: La Dogana di Milano
    lat: 45.463397
    lon: 9.189293
    logo: logo_ladogana.png
    addr: Via Dogana 2, 20123 Milano
    no_home_map: false
  - id: google
    url: https://www.google.com/
    name: Google
    lat: 45.486167
    lon: 9.189544
    logo: logo_google.png
    addr: Via Federico Confalonieri 4, 20124 Milano
    no_home_map: false
  - id: mikamai
    url: https://www.mikamai.com/
    name: Mikamai/LinkMe
    lat: 45.490600
    lon: 9.215171
    logo: logo_mikamai.png
    addr: Via Giulio e Corrado Venini 42, 20127 Milano
    no_home_map: false
  - id: fondazione_prada
    url: //www.fondazioneprada.org/
    name: Fondazione Prada
    lat: 45.444374
    lon: 9.205253
    logo: logo_fondazione_prada.png
    addr: Largo Isarco, 2, 20139 Milano
    no_home_map: true
  - id: ied
    url: https://www.ied.it/
    name: IED
    lat: 45.4615582
    lon: 9.20934490000002
    logo: logo_ied.png
    addr: Via Amatore Sciesa, 4, 20135 Milano
  - id: politecnico
    url: https://www.polimi.it/
    name: Politecnico - Bovisa
    lat: 45.50237
    lon: 9.1558413
    logo: logo_politecnico.png
    addr: Via Lambruschini, 4, 20146 Milano
  - id: mm
    url: https://www.mmspa.eu/
    name: MM Centrale dell'Acqua di Milano
    lat: 45.4873268
    lon: 9.1634932
    logo: logo_mm.png
    addr: Piazza Diocleziano, 5, 20154 Milano
  - id: fastweb
    url: https://www.fastweb.it/
    name: Fastweb
    lat: 45.4428686
    lon: 9.2015771
    logo: logo_fastweb.png
    addr: Piazza Adriano Olivetti,1, 20139 Milano
  - id: fgb_luiss
    url: https://www.luiss.it/
    name: FGB @milano Luiss Hub for makers and students
    lat: 45.4831495
    lon: 9.1821101
    logo: logo_fgb.jpg
    addr: Via Massimo D'Azeglio, 3, 20154 Milano
  - id: statale_mi_informatica
    url: https://www.unimi.it
    name: Università degli Studi di Milano
    lat: 45.4760027
    lon: 9.2318815
    logo: logo_unimi.png
    addr: Via G. Celoria, 18, 20133 Milano - Dipartimento di Informatica

# Build settings
markdown: kramdown
permalink: pretty

collections:
  mentors:
    output: no
  tutorials:
    output: yes
    path: /tutorials/:name
  tools:
    output: yes
    path: /tools/:name

plugins_dir:
 - jekyll-coffeescript
 - jekyll-redirect-from
