# Site settings
title: CoderDojo Milano
url: http://www.coderdojomilano.it
description: "Dedicato a ragazzi e ragazze di età compresa tra i 7 e 17 anni che vogliono imparare a programmare, divertendosi"
storage_uuid: "a26d6629-e365-4dea-8d40-dcf0d1b3a1aa"
timezone: Europe/Rome
future: True

# Color settings
color:
  bg: '#efefef'
  fg: '#3f3f3f'
  navbar: 'rgba(255,255,255,.8)'
  navbar-collapsed: 'rgba(255,255,255,1)'
  links: '#000'
  links-focus: '#00f'

# Socials
social:
  - title: google-plus
    url: https://plus.google.com/+CoderdojomilanoIt
  - title: facebook
    url: https://www.facebook.com/CoderDojoMi
  - title: twitter
    url: https://twitter.com/CoderDojoMi

event_locations:
  - id: tagmilano
    url: http://talentgarden.org
    name: TAG Milano
    lat: 45.4973345
    lon: 9.2191134
    logo: logo_tag_milano.png
    addr: Via Merano, 16, 20127 Milano
  - id: wemake
    url: http://wemake.cc
    name: WeMake
    lat: 45.507106
    lon: 9.2262703
    logo: logo_wemake.png
    addr: Via Privata Stefanardo da Vimercate, 27, 20128 Milano
  - id: wcapmi
    url: http://www.wcap.tim.it/en/accelerators/milan
    name: Working Capital Accelerator
    lat: 45.4862554
    lon: 9.2425329
    logo: logo_wcap.png
    addr: Via Rombon, 52, 20134 Milano
# Build settings
markdown: kramdown
permalink: pretty

collections:
  mentors:
    output: no
  tutorials:
    output: yes
    path: /tutorials/:name
  tools:
    output: yes
    path: /tools/:name

gems:
 - jekyll-coffeescript
 - jekyll-redirect-from

